theme: minima
title: Vanessa's Homepage
author: Vanessa Yao
email: vanessa.yao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Vanessa's homepage from github-pages tutorial! 
  Current date: 09/21/2020

# social links
twitter_username: n/a # DO NOT include the @ character, or else the build will fail!
github_username:  vanessa-yao # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
